name: native_download_manager
description: "A production-ready Flutter package providing native background download capability for Android and iOS."
version: 1.0.5


homepage: https://github.com/adityaku/native_download_manager

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  path_provider: ^2.1.2
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  pigeon: ^17.3.0

flutter:
  plugin:
    platforms:
      android:
        package: com.native_download_manager
        pluginClass: NativeDownloadManagerPlugin
      ios:
        pluginClass: NativeDownloadManagerPlugin
