// Autogenerated from Pigeon (v17.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> FlutterError {
  return FlutterError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Generated class from Pigeon that represents data sent in messages.
struct PigeonDownloadRequest {
  var id: String
  var url: String
  var fileName: String
  var destinationDirectory: String? = nil
  var headers: [String?: String?]
  var wifiOnly: Bool
  var chargingOnly: Bool
  var requiresBatteryNotLow: Bool
  var priority: Int64
  var checksum: String? = nil
  var checksumAlgorithm: String? = nil
  var overwrite: Bool

  static func fromList(_ list: [Any?]) -> PigeonDownloadRequest? {
    let id = list[0] as! String
    let url = list[1] as! String
    let fileName = list[2] as! String
    let destinationDirectory: String? = nilOrValue(list[3])
    let headers = list[4] as! [String?: String?]
    let wifiOnly = list[5] as! Bool
    let chargingOnly = list[6] as! Bool
    let requiresBatteryNotLow = list[7] as! Bool
    let priority = list[8] is Int64 ? list[8] as! Int64 : Int64(list[8] as! Int32)
    let checksum: String? = nilOrValue(list[9])
    let checksumAlgorithm: String? = nilOrValue(list[10])
    let overwrite = list[11] as! Bool

    return PigeonDownloadRequest(
      id: id,
      url: url,
      fileName: fileName,
      destinationDirectory: destinationDirectory,
      headers: headers,
      wifiOnly: wifiOnly,
      chargingOnly: chargingOnly,
      requiresBatteryNotLow: requiresBatteryNotLow,
      priority: priority,
      checksum: checksum,
      checksumAlgorithm: checksumAlgorithm,
      overwrite: overwrite
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      url,
      fileName,
      destinationDirectory,
      headers,
      wifiOnly,
      chargingOnly,
      requiresBatteryNotLow,
      priority,
      checksum,
      checksumAlgorithm,
      overwrite,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PigeonDownloadTask {
  var id: String
  var url: String
  var fileName: String
  var filePath: String? = nil
  var status: Int64
  var progress: Double
  var downloadedBytes: Int64
  var totalBytes: Int64
  var speed: Double
  var etaSeconds: Int64
  var error: String? = nil

  static func fromList(_ list: [Any?]) -> PigeonDownloadTask? {
    let id = list[0] as! String
    let url = list[1] as! String
    let fileName = list[2] as! String
    let filePath: String? = nilOrValue(list[3])
    let status = list[4] is Int64 ? list[4] as! Int64 : Int64(list[4] as! Int32)
    let progress = list[5] as! Double
    let downloadedBytes = list[6] is Int64 ? list[6] as! Int64 : Int64(list[6] as! Int32)
    let totalBytes = list[7] is Int64 ? list[7] as! Int64 : Int64(list[7] as! Int32)
    let speed = list[8] as! Double
    let etaSeconds = list[9] is Int64 ? list[9] as! Int64 : Int64(list[9] as! Int32)
    let error: String? = nilOrValue(list[10])

    return PigeonDownloadTask(
      id: id,
      url: url,
      fileName: fileName,
      filePath: filePath,
      status: status,
      progress: progress,
      downloadedBytes: downloadedBytes,
      totalBytes: totalBytes,
      speed: speed,
      etaSeconds: etaSeconds,
      error: error
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      url,
      fileName,
      filePath,
      status,
      progress,
      downloadedBytes,
      totalBytes,
      speed,
      etaSeconds,
      error,
    ]
  }
}
private class NativeDownloadManagerHostApiCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 128:
      return PigeonDownloadRequest.fromList(self.readValue() as! [Any?])
    case 129:
      return PigeonDownloadTask.fromList(self.readValue() as! [Any?])
    case 130:
      return PigeonDownloadTask.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class NativeDownloadManagerHostApiCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? PigeonDownloadRequest {
      super.writeByte(128)
      super.writeValue(value.toList())
    } else if let value = value as? PigeonDownloadTask {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? PigeonDownloadTask {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class NativeDownloadManagerHostApiCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return NativeDownloadManagerHostApiCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return NativeDownloadManagerHostApiCodecWriter(data: data)
  }
}

class NativeDownloadManagerHostApiCodec: FlutterStandardMessageCodec {
  static let shared = NativeDownloadManagerHostApiCodec(readerWriter: NativeDownloadManagerHostApiCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol NativeDownloadManagerHostApi {
  func initialize() throws
  func startDownload(request: PigeonDownloadRequest) throws
  func pauseDownload(taskId: String) throws
  func resumeDownload(taskId: String) throws
  func cancelDownload(taskId: String) throws
  func retryDownload(taskId: String) throws
  func deleteDownload(taskId: String, deleteFile: Bool) throws
  func getAllTasks() throws -> [PigeonDownloadTask]
  func getTask(taskId: String) throws -> PigeonDownloadTask?
  func clearHistory() throws
  func setConcurrencyLimit(limit: Int64) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class NativeDownloadManagerHostApiSetup {
  /// The codec used by NativeDownloadManagerHostApi.
  static var codec: FlutterStandardMessageCodec { NativeDownloadManagerHostApiCodec.shared }
  /// Sets up an instance of `NativeDownloadManagerHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: NativeDownloadManagerHostApi?) {
    let initializeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_download_manager.NativeDownloadManagerHostApi.initialize", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeChannel.setMessageHandler { _, reply in
        do {
          try api.initialize()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      initializeChannel.setMessageHandler(nil)
    }
    let startDownloadChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_download_manager.NativeDownloadManagerHostApi.startDownload", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startDownloadChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! PigeonDownloadRequest
        do {
          try api.startDownload(request: requestArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startDownloadChannel.setMessageHandler(nil)
    }
    let pauseDownloadChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_download_manager.NativeDownloadManagerHostApi.pauseDownload", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pauseDownloadChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let taskIdArg = args[0] as! String
        do {
          try api.pauseDownload(taskId: taskIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      pauseDownloadChannel.setMessageHandler(nil)
    }
    let resumeDownloadChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_download_manager.NativeDownloadManagerHostApi.resumeDownload", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      resumeDownloadChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let taskIdArg = args[0] as! String
        do {
          try api.resumeDownload(taskId: taskIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      resumeDownloadChannel.setMessageHandler(nil)
    }
    let cancelDownloadChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_download_manager.NativeDownloadManagerHostApi.cancelDownload", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelDownloadChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let taskIdArg = args[0] as! String
        do {
          try api.cancelDownload(taskId: taskIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      cancelDownloadChannel.setMessageHandler(nil)
    }
    let retryDownloadChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_download_manager.NativeDownloadManagerHostApi.retryDownload", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      retryDownloadChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let taskIdArg = args[0] as! String
        do {
          try api.retryDownload(taskId: taskIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      retryDownloadChannel.setMessageHandler(nil)
    }
    let deleteDownloadChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_download_manager.NativeDownloadManagerHostApi.deleteDownload", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      deleteDownloadChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let taskIdArg = args[0] as! String
        let deleteFileArg = args[1] as! Bool
        do {
          try api.deleteDownload(taskId: taskIdArg, deleteFile: deleteFileArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      deleteDownloadChannel.setMessageHandler(nil)
    }
    let getAllTasksChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_download_manager.NativeDownloadManagerHostApi.getAllTasks", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getAllTasksChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getAllTasks()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getAllTasksChannel.setMessageHandler(nil)
    }
    let getTaskChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_download_manager.NativeDownloadManagerHostApi.getTask", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getTaskChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let taskIdArg = args[0] as! String
        do {
          let result = try api.getTask(taskId: taskIdArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getTaskChannel.setMessageHandler(nil)
    }
    let clearHistoryChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_download_manager.NativeDownloadManagerHostApi.clearHistory", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      clearHistoryChannel.setMessageHandler { _, reply in
        do {
          try api.clearHistory()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      clearHistoryChannel.setMessageHandler(nil)
    }
    let setConcurrencyLimitChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_download_manager.NativeDownloadManagerHostApi.setConcurrencyLimit", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setConcurrencyLimitChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let limitArg = args[0] is Int64 ? args[0] as! Int64 : Int64(args[0] as! Int32)
        do {
          try api.setConcurrencyLimit(limit: limitArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setConcurrencyLimitChannel.setMessageHandler(nil)
    }
  }
}
private class NativeDownloadManagerFlutterApiCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 128:
      return PigeonDownloadTask.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class NativeDownloadManagerFlutterApiCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? PigeonDownloadTask {
      super.writeByte(128)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class NativeDownloadManagerFlutterApiCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return NativeDownloadManagerFlutterApiCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return NativeDownloadManagerFlutterApiCodecWriter(data: data)
  }
}

class NativeDownloadManagerFlutterApiCodec: FlutterStandardMessageCodec {
  static let shared = NativeDownloadManagerFlutterApiCodec(readerWriter: NativeDownloadManagerFlutterApiCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol NativeDownloadManagerFlutterApiProtocol {
  func onTaskStatusChanged(task taskArg: PigeonDownloadTask, completion: @escaping (Result<Void, FlutterError>) -> Void)
  func onTaskProgressUpdated(taskId taskIdArg: String, downloadedBytes downloadedBytesArg: Int64, totalBytes totalBytesArg: Int64, speed speedArg: Double, etaSeconds etaSecondsArg: Int64, completion: @escaping (Result<Void, FlutterError>) -> Void)
}
class NativeDownloadManagerFlutterApi: NativeDownloadManagerFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  init(binaryMessenger: FlutterBinaryMessenger) {
    self.binaryMessenger = binaryMessenger
  }
  var codec: FlutterStandardMessageCodec {
    return NativeDownloadManagerFlutterApiCodec.shared
  }
  func onTaskStatusChanged(task taskArg: PigeonDownloadTask, completion: @escaping (Result<Void, FlutterError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.native_download_manager.NativeDownloadManagerFlutterApi.onTaskStatusChanged"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([taskArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(FlutterError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onTaskProgressUpdated(taskId taskIdArg: String, downloadedBytes downloadedBytesArg: Int64, totalBytes totalBytesArg: Int64, speed speedArg: Double, etaSeconds etaSecondsArg: Int64, completion: @escaping (Result<Void, FlutterError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.native_download_manager.NativeDownloadManagerFlutterApi.onTaskProgressUpdated"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([taskIdArg, downloadedBytesArg, totalBytesArg, speedArg, etaSecondsArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(FlutterError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
}
