// Autogenerated from Pigeon (v17.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package com.native_download_manager

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  if (exception is FlutterError) {
    return listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    return listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

private fun createConnectionError(channelName: String): FlutterError {
  return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Generated class from Pigeon that represents data sent in messages. */
data class PigeonDownloadRequest (
  val id: String,
  val url: String,
  val fileName: String,
  val destinationDirectory: String? = null,
  val headers: Map<String?, String?>,
  val wifiOnly: Boolean,
  val chargingOnly: Boolean,
  val requiresBatteryNotLow: Boolean,
  val priority: Long,
  val checksum: String? = null,
  val checksumAlgorithm: String? = null,
  val overwrite: Boolean

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): PigeonDownloadRequest {
      val id = list[0] as String
      val url = list[1] as String
      val fileName = list[2] as String
      val destinationDirectory = list[3] as String?
      val headers = list[4] as Map<String?, String?>
      val wifiOnly = list[5] as Boolean
      val chargingOnly = list[6] as Boolean
      val requiresBatteryNotLow = list[7] as Boolean
      val priority = list[8].let { if (it is Int) it.toLong() else it as Long }
      val checksum = list[9] as String?
      val checksumAlgorithm = list[10] as String?
      val overwrite = list[11] as Boolean
      return PigeonDownloadRequest(id, url, fileName, destinationDirectory, headers, wifiOnly, chargingOnly, requiresBatteryNotLow, priority, checksum, checksumAlgorithm, overwrite)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      id,
      url,
      fileName,
      destinationDirectory,
      headers,
      wifiOnly,
      chargingOnly,
      requiresBatteryNotLow,
      priority,
      checksum,
      checksumAlgorithm,
      overwrite,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PigeonDownloadTask (
  val id: String,
  val url: String,
  val fileName: String,
  val filePath: String? = null,
  val status: Long,
  val progress: Double,
  val downloadedBytes: Long,
  val totalBytes: Long,
  val speed: Double,
  val etaSeconds: Long,
  val error: String? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): PigeonDownloadTask {
      val id = list[0] as String
      val url = list[1] as String
      val fileName = list[2] as String
      val filePath = list[3] as String?
      val status = list[4].let { if (it is Int) it.toLong() else it as Long }
      val progress = list[5] as Double
      val downloadedBytes = list[6].let { if (it is Int) it.toLong() else it as Long }
      val totalBytes = list[7].let { if (it is Int) it.toLong() else it as Long }
      val speed = list[8] as Double
      val etaSeconds = list[9].let { if (it is Int) it.toLong() else it as Long }
      val error = list[10] as String?
      return PigeonDownloadTask(id, url, fileName, filePath, status, progress, downloadedBytes, totalBytes, speed, etaSeconds, error)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      id,
      url,
      fileName,
      filePath,
      status,
      progress,
      downloadedBytes,
      totalBytes,
      speed,
      etaSeconds,
      error,
    )
  }
}
@Suppress("UNCHECKED_CAST")
private object NativeDownloadManagerHostApiCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      128.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PigeonDownloadRequest.fromList(it)
        }
      }
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PigeonDownloadTask.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PigeonDownloadTask.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is PigeonDownloadRequest -> {
        stream.write(128)
        writeValue(stream, value.toList())
      }
      is PigeonDownloadTask -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is PigeonDownloadTask -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface NativeDownloadManagerHostApi {
  fun initialize()
  fun startDownload(request: PigeonDownloadRequest)
  fun pauseDownload(taskId: String)
  fun resumeDownload(taskId: String)
  fun cancelDownload(taskId: String)
  fun retryDownload(taskId: String)
  fun deleteDownload(taskId: String, deleteFile: Boolean)
  fun getAllTasks(): List<PigeonDownloadTask>
  fun getTask(taskId: String): PigeonDownloadTask?
  fun clearHistory()
  fun setConcurrencyLimit(limit: Long)

  companion object {
    /** The codec used by NativeDownloadManagerHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      NativeDownloadManagerHostApiCodec
    }
    /** Sets up an instance of `NativeDownloadManagerHostApi` to handle messages through the `binaryMessenger`. */
    @Suppress("UNCHECKED_CAST")
    fun setUp(binaryMessenger: BinaryMessenger, api: NativeDownloadManagerHostApi?) {
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.native_download_manager.NativeDownloadManagerHostApi.initialize", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            var wrapped: List<Any?>
            try {
              api.initialize()
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.native_download_manager.NativeDownloadManagerHostApi.startDownload", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as PigeonDownloadRequest
            var wrapped: List<Any?>
            try {
              api.startDownload(requestArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.native_download_manager.NativeDownloadManagerHostApi.pauseDownload", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val taskIdArg = args[0] as String
            var wrapped: List<Any?>
            try {
              api.pauseDownload(taskIdArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.native_download_manager.NativeDownloadManagerHostApi.resumeDownload", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val taskIdArg = args[0] as String
            var wrapped: List<Any?>
            try {
              api.resumeDownload(taskIdArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.native_download_manager.NativeDownloadManagerHostApi.cancelDownload", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val taskIdArg = args[0] as String
            var wrapped: List<Any?>
            try {
              api.cancelDownload(taskIdArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.native_download_manager.NativeDownloadManagerHostApi.retryDownload", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val taskIdArg = args[0] as String
            var wrapped: List<Any?>
            try {
              api.retryDownload(taskIdArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.native_download_manager.NativeDownloadManagerHostApi.deleteDownload", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val taskIdArg = args[0] as String
            val deleteFileArg = args[1] as Boolean
            var wrapped: List<Any?>
            try {
              api.deleteDownload(taskIdArg, deleteFileArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.native_download_manager.NativeDownloadManagerHostApi.getAllTasks", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            var wrapped: List<Any?>
            try {
              wrapped = listOf<Any?>(api.getAllTasks())
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.native_download_manager.NativeDownloadManagerHostApi.getTask", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val taskIdArg = args[0] as String
            var wrapped: List<Any?>
            try {
              wrapped = listOf<Any?>(api.getTask(taskIdArg))
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.native_download_manager.NativeDownloadManagerHostApi.clearHistory", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            var wrapped: List<Any?>
            try {
              api.clearHistory()
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.native_download_manager.NativeDownloadManagerHostApi.setConcurrencyLimit", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val limitArg = args[0].let { if (it is Int) it.toLong() else it as Long }
            var wrapped: List<Any?>
            try {
              api.setConcurrencyLimit(limitArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
@Suppress("UNCHECKED_CAST")
private object NativeDownloadManagerFlutterApiCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      128.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PigeonDownloadTask.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is PigeonDownloadTask -> {
        stream.write(128)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
@Suppress("UNCHECKED_CAST")
class NativeDownloadManagerFlutterApi(private val binaryMessenger: BinaryMessenger) {
  companion object {
    /** The codec used by NativeDownloadManagerFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      NativeDownloadManagerFlutterApiCodec
    }
  }
  fun onTaskStatusChanged(taskArg: PigeonDownloadTask, callback: (Result<Unit>) -> Unit)
{
    val channelName = "dev.flutter.pigeon.native_download_manager.NativeDownloadManagerFlutterApi.onTaskStatusChanged"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(taskArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onTaskProgressUpdated(taskIdArg: String, downloadedBytesArg: Long, totalBytesArg: Long, speedArg: Double, etaSecondsArg: Long, callback: (Result<Unit>) -> Unit)
{
    val channelName = "dev.flutter.pigeon.native_download_manager.NativeDownloadManagerFlutterApi.onTaskProgressUpdated"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(taskIdArg, downloadedBytesArg, totalBytesArg, speedArg, etaSecondsArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
}
