// Autogenerated from Pigeon (v17.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

class PigeonDownloadRequest {
  PigeonDownloadRequest({
    required this.id,
    required this.url,
    required this.fileName,
    this.destinationDirectory,
    required this.headers,
    required this.wifiOnly,
    required this.chargingOnly,
    required this.requiresBatteryNotLow,
    required this.priority,
    this.checksum,
    this.checksumAlgorithm,
    required this.overwrite,
  });

  String id;

  String url;

  String fileName;

  String? destinationDirectory;

  Map<String?, String?> headers;

  bool wifiOnly;

  bool chargingOnly;

  bool requiresBatteryNotLow;

  int priority;

  String? checksum;

  String? checksumAlgorithm;

  bool overwrite;

  Object encode() {
    return <Object?>[
      id,
      url,
      fileName,
      destinationDirectory,
      headers,
      wifiOnly,
      chargingOnly,
      requiresBatteryNotLow,
      priority,
      checksum,
      checksumAlgorithm,
      overwrite,
    ];
  }

  static PigeonDownloadRequest decode(Object result) {
    result as List<Object?>;
    return PigeonDownloadRequest(
      id: result[0]! as String,
      url: result[1]! as String,
      fileName: result[2]! as String,
      destinationDirectory: result[3] as String?,
      headers: (result[4] as Map<Object?, Object?>?)!.cast<String?, String?>(),
      wifiOnly: result[5]! as bool,
      chargingOnly: result[6]! as bool,
      requiresBatteryNotLow: result[7]! as bool,
      priority: result[8]! as int,
      checksum: result[9] as String?,
      checksumAlgorithm: result[10] as String?,
      overwrite: result[11]! as bool,
    );
  }
}

class PigeonDownloadTask {
  PigeonDownloadTask({
    required this.id,
    required this.url,
    required this.fileName,
    this.filePath,
    required this.status,
    required this.progress,
    required this.downloadedBytes,
    required this.totalBytes,
    required this.speed,
    required this.etaSeconds,
    this.error,
  });

  String id;

  String url;

  String fileName;

  String? filePath;

  int status;

  double progress;

  int downloadedBytes;

  int totalBytes;

  double speed;

  int etaSeconds;

  String? error;

  Object encode() {
    return <Object?>[
      id,
      url,
      fileName,
      filePath,
      status,
      progress,
      downloadedBytes,
      totalBytes,
      speed,
      etaSeconds,
      error,
    ];
  }

  static PigeonDownloadTask decode(Object result) {
    result as List<Object?>;
    return PigeonDownloadTask(
      id: result[0]! as String,
      url: result[1]! as String,
      fileName: result[2]! as String,
      filePath: result[3] as String?,
      status: result[4]! as int,
      progress: result[5]! as double,
      downloadedBytes: result[6]! as int,
      totalBytes: result[7]! as int,
      speed: result[8]! as double,
      etaSeconds: result[9]! as int,
      error: result[10] as String?,
    );
  }
}

class _NativeDownloadManagerHostApiCodec extends StandardMessageCodec {
  const _NativeDownloadManagerHostApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is PigeonDownloadRequest) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else if (value is PigeonDownloadTask) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is PigeonDownloadTask) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return PigeonDownloadRequest.decode(readValue(buffer)!);
      case 129: 
        return PigeonDownloadTask.decode(readValue(buffer)!);
      case 130: 
        return PigeonDownloadTask.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class NativeDownloadManagerHostApi {
  /// Constructor for [NativeDownloadManagerHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  NativeDownloadManagerHostApi({BinaryMessenger? binaryMessenger})
      : __pigeon_binaryMessenger = binaryMessenger;
  final BinaryMessenger? __pigeon_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _NativeDownloadManagerHostApiCodec();

  Future<void> initialize() async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.native_download_manager.NativeDownloadManagerHostApi.initialize';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(null) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> startDownload(PigeonDownloadRequest request) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.native_download_manager.NativeDownloadManagerHostApi.startDownload';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[request]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> pauseDownload(String taskId) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.native_download_manager.NativeDownloadManagerHostApi.pauseDownload';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[taskId]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> resumeDownload(String taskId) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.native_download_manager.NativeDownloadManagerHostApi.resumeDownload';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[taskId]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> cancelDownload(String taskId) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.native_download_manager.NativeDownloadManagerHostApi.cancelDownload';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[taskId]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> retryDownload(String taskId) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.native_download_manager.NativeDownloadManagerHostApi.retryDownload';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[taskId]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> deleteDownload(String taskId, bool deleteFile) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.native_download_manager.NativeDownloadManagerHostApi.deleteDownload';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[taskId, deleteFile]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<List<PigeonDownloadTask?>> getAllTasks() async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.native_download_manager.NativeDownloadManagerHostApi.getAllTasks';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(null) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as List<Object?>?)!.cast<PigeonDownloadTask?>();
    }
  }

  Future<PigeonDownloadTask?> getTask(String taskId) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.native_download_manager.NativeDownloadManagerHostApi.getTask';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[taskId]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return (__pigeon_replyList[0] as PigeonDownloadTask?);
    }
  }

  Future<void> clearHistory() async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.native_download_manager.NativeDownloadManagerHostApi.clearHistory';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(null) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> setConcurrencyLimit(int limit) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.native_download_manager.NativeDownloadManagerHostApi.setConcurrencyLimit';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[limit]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }
}

class _NativeDownloadManagerFlutterApiCodec extends StandardMessageCodec {
  const _NativeDownloadManagerFlutterApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is PigeonDownloadTask) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return PigeonDownloadTask.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

abstract class NativeDownloadManagerFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _NativeDownloadManagerFlutterApiCodec();

  void onTaskStatusChanged(PigeonDownloadTask task);

  void onTaskProgressUpdated(String taskId, int downloadedBytes, int totalBytes, double speed, int etaSeconds);

  static void setup(NativeDownloadManagerFlutterApi? api, {BinaryMessenger? binaryMessenger}) {
    {
      final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.native_download_manager.NativeDownloadManagerFlutterApi.onTaskStatusChanged', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        __pigeon_channel.setMessageHandler(null);
      } else {
        __pigeon_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.native_download_manager.NativeDownloadManagerFlutterApi.onTaskStatusChanged was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final PigeonDownloadTask? arg_task = (args[0] as PigeonDownloadTask?);
          assert(arg_task != null,
              'Argument for dev.flutter.pigeon.native_download_manager.NativeDownloadManagerFlutterApi.onTaskStatusChanged was null, expected non-null PigeonDownloadTask.');
          try {
            api.onTaskStatusChanged(arg_task!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.native_download_manager.NativeDownloadManagerFlutterApi.onTaskProgressUpdated', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        __pigeon_channel.setMessageHandler(null);
      } else {
        __pigeon_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.native_download_manager.NativeDownloadManagerFlutterApi.onTaskProgressUpdated was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_taskId = (args[0] as String?);
          assert(arg_taskId != null,
              'Argument for dev.flutter.pigeon.native_download_manager.NativeDownloadManagerFlutterApi.onTaskProgressUpdated was null, expected non-null String.');
          final int? arg_downloadedBytes = (args[1] as int?);
          assert(arg_downloadedBytes != null,
              'Argument for dev.flutter.pigeon.native_download_manager.NativeDownloadManagerFlutterApi.onTaskProgressUpdated was null, expected non-null int.');
          final int? arg_totalBytes = (args[2] as int?);
          assert(arg_totalBytes != null,
              'Argument for dev.flutter.pigeon.native_download_manager.NativeDownloadManagerFlutterApi.onTaskProgressUpdated was null, expected non-null int.');
          final double? arg_speed = (args[3] as double?);
          assert(arg_speed != null,
              'Argument for dev.flutter.pigeon.native_download_manager.NativeDownloadManagerFlutterApi.onTaskProgressUpdated was null, expected non-null double.');
          final int? arg_etaSeconds = (args[4] as int?);
          assert(arg_etaSeconds != null,
              'Argument for dev.flutter.pigeon.native_download_manager.NativeDownloadManagerFlutterApi.onTaskProgressUpdated was null, expected non-null int.');
          try {
            api.onTaskProgressUpdated(arg_taskId!, arg_downloadedBytes!, arg_totalBytes!, arg_speed!, arg_etaSeconds!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
